Sewit/Controllers/SleeveController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sewit.Contracts;
using Sewit.Data;
using Sewit.Models;
using Sewit.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sewit.Controllers
{
    [Authorize]
    public class SleeveController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ISleeveComponentRepository _sleeveComponentRepository;
        private readonly IPhotoUploadService _photoUploadService;

        public SleeveController(IMapper mapper, ISleeveComponentRepository sleeveComponentRepository, IPhotoUploadService photoUploadService)
        {
            _mapper = mapper;
            _sleeveComponentRepository = sleeveComponentRepository;
            _photoUploadService = photoUploadService;
        }

        public IActionResult Index()
        {
            var sleeves = _sleeveComponentRepository.FindAll();
            var model = _mapper.Map<List<SleeveComponentVM>>(sleeves);
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SleeveComponentCreateVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var sleeve = _mapper.Map<SleeveComponent>(model);

            sleeve.PhotoPath = _photoUploadService.UploadImage(model.Photo);
            _sleeveComponentRepository.Create(sleeve);

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var sleeve = _sleeveComponentRepository.FindById(id);
            var model = _mapper.Map<SleeveComponentEditVM>(sleeve);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SleeveComponentEditVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var sleeve = _mapper.Map<SleeveComponent>(model);
            _sleeveComponentRepository.Update(sleeve);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var sleeve = _sleeveComponentRepository.FindById(id);
            _sleeveComponentRepository.Delete(sleeve);

            return RedirectToAction("Index");
        }
    }
}

Sewit/Views/Sleeve/Create.cshtml
@model Sewit.Models.SleeveComponentCreateVM

@{
    ViewData["Title"] = "Create";
}
<div class="container">
    <h1>Create</h1>

    <h4>Sleeve Component</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group form-control-file custom-file-input">
                    <label asp-for="Photo" class="control-label"></label>
                    <div class="custom-file">
                        <input asp-for="Photo" class="form-control custom-file-input" />
                        <label class="custom-file-label">Choose Image...</label>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>


</div>

@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var filename = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(filename);
            });
        });
    </script>
}

Sewit/Views/Sleeve/Index.cshtml
@model IEnumerable<Sewit.Models.SleeveComponentVM>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <p>
        <a class="btn btn-success" asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhotoPath)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <div class="card" style="height: 211px; width: 150px">
                            <img src=@item.PhotoPath class="card-img-top img-preview" />
                        </div>
                    </td>
                    <td>
                        <a class="btn btn-danger" asp-controller="Sleeve" asp-action="Delete" asp-route-id=@item.SleeveId><i class="fa fa-trash"></i> Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>