Sewit/Controllers/DesignController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Sewit.Contracts;
using Sewit.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sewit.Controllers
{
    public class DesignController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IDressRepository _dressRepository;
        private readonly ITopComponentRepository _topComponentRepository;
        private readonly ISkirtComponentRepository _skirtComponentRepository;
        private readonly ISleeveComponentRepository _sleeveComponentRepository;
        private readonly IRecommendationService _recommendationService;
        private static Dictionary<string, int> _preferences;


        public DesignController(IMapper mapper,
                                ITopComponentRepository topComponentRepository,
                                ISkirtComponentRepository skirtComponentRepository,
                                ISleeveComponentRepository sleeveComponentRepository)
        {
            _mapper = mapper;
            _topComponentRepository = topComponentRepository;
            _skirtComponentRepository = skirtComponentRepository;
            _sleeveComponentRepository = sleeveComponentRepository;

        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Sewit/Controllers/DressController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sewit.Contracts;
using Sewit.Data;
using Sewit.Models;
using Sewit.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sewit.Controllers
{
    [Authorize]
    public class DressController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IDressRepository _dressRepository;
        private readonly ITopComponentRepository _topComponentRepository;
        private readonly IPhotoUploadService _photoUploadService;
        private readonly IRecommendationService _recommendationService;
        private readonly ISleeveComponentRepository _sleeveComponentRepository;
        private readonly ISkirtComponentRepository _skirtComponentRepository;

        public DressController(IMapper mapper, 
                               IDressRepository dressRepository,
                               ITopComponentRepository topComponentRepository,
                               ISleeveComponentRepository sleeveComponentRepository,
                               ISkirtComponentRepository skirtComponentRepository,
                               IPhotoUploadService photoUploadService, 
                               IRecommendationService recommendationService)
        {
            _mapper = mapper;
            _dressRepository = dressRepository;
            _topComponentRepository = topComponentRepository;
            _sleeveComponentRepository = sleeveComponentRepository;
            _skirtComponentRepository = skirtComponentRepository;
            _photoUploadService = photoUploadService;
            _recommendationService = recommendationService;
        }

        
        public IActionResult Index()
        {
            var dresses = _dressRepository.FindAll();
            var model = _mapper.Map<List<DressVM>>(dresses);
            return View(model);
        }

        public IActionResult Create()
        {
            ViewBag.Tops = _topComponentRepository.FindAll();
            ViewBag.Sleeves = _sleeveComponentRepository.FindAll();
            ViewBag.Skirts = _skirtComponentRepository.FindAll();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DressCreateVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var dress = _mapper.Map<Dress>(model);

            dress.PhotoPath = _photoUploadService.UploadImage(model.Photo);
            _dressRepository.Create(dress);

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var dress = _dressRepository.FindById(id);
            var model = _mapper.Map<DressEditVM>(dress);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(DressEditVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var dress = _mapper.Map<Dress>(model);

            
            _dressRepository.Update(dress);

            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var dress = _dressRepository.FindById(id); // Retrieve dress

            var categories = new Dictionary<string, int>()
            {
                { "Top", dress.TopId },
                { "Skirt", dress.SkirtId },
                { "Sleeve", dress.SleeveId }
            };

            // Get 4 recommendations based on this dress
            var recommendations = _recommendationService.RecommnedDresses(categories, id)
                                                        .Where(d=>d.DressId != dress.DressId)
                                                        .Take(4)
                                                        .ToList();

            ViewBag.Recommendations = _mapper.Map<List<DressVM>>(recommendations);

            var model = _mapper.Map<DressVM>(dress);
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            var dress = _dressRepository.FindById(id);
            _dressRepository.Delete(dress);

            return RedirectToAction("Index");
        }
    }
}

Sewit/Controllers/OrderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sewit.Contracts;
using Sewit.Data;
using Sewit.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sewit.Controllers
{
    [AllowAnonymous]
    public class OrderController : Controller
    {
        private static OrderVM order = new OrderVM()
        {
            Dresses = new List<DressVM>()
        };
        private readonly IDressRepository _dressRepository;
        private readonly IMapper _mapper;

        public OrderController(IDressRepository dressRepository, IMapper mapper)
        {
            _dressRepository = dressRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View(order);
        }

        public IActionResult AddItem(DressVM dress)
        {
            var size = dress.SelectedSize;
            dress = _mapper.Map<DressVM>(_dressRepository.FindById(dress.DressId));
            dress.SelectedSize = size;
            order.Dresses.Add(dress); // Add dress to cart
            order.TotalPrice = order.Dresses.Sum(d => d.Price); // Calculate total price
            return RedirectToAction("Index");
        }

        public IActionResult RemoveItem(int id)
        {
            order.Dresses.RemoveAll(d => d.DressId == id);
            order.TotalPrice = order.Dresses.Sum(d => d.Price);
            return RedirectToAction("Index");

        }

        public IActionResult CompleteOrder()
        {
            order.Dresses.Clear();
            order.TotalPrice = 0;
            return View();
        }
    }
}

Sewit/Controllers/SewController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Sewit.Contracts;
using Sewit.Data;
using Sewit.Models;
using Sewit.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sewit.Controllers
{
    public class SewController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IDressRepository _dressRepository;
        private readonly ITopComponentRepository _topComponentRepository;
        private readonly ISkirtComponentRepository _skirtComponentRepository;
        private readonly ISleeveComponentRepository _sleeveComponentRepository;
        private readonly IRecommendationService _recommendationService;
        private static Dictionary<string, int> _preferences;


        public SewController(IMapper mapper,
                             IDressRepository dressRepository,
                             ITopComponentRepository topComponentRepository,
                             ISkirtComponentRepository skirtComponentRepository,
                             ISleeveComponentRepository sleeveComponentRepository,
                             IRecommendationService recommendationService)
        {
            _mapper = mapper;
            _dressRepository = dressRepository;
            _topComponentRepository = topComponentRepository;
            _skirtComponentRepository = skirtComponentRepository;
            _sleeveComponentRepository = sleeveComponentRepository;
            _recommendationService = recommendationService;

        }

        public IActionResult Index()
        {
            _preferences = new Dictionary<string, int>(); // Initialize the preferences of the user

            var allDresses = _dressRepository.FindAll(); // Get 4 random dresses for the 'Our work' section
            var ourWork = new List<Dress>();
            var random = new Random();
            for(int i = 0; i < 4; i++)
            {
                int index = random.Next(allDresses.Count);
                ourWork.Add(allDresses[index]);
            }

            var model = _mapper.Map<List<DressVM>>(ourWork);
            return View(model);
        }

        public IActionResult Top()
        {
            var tops = _topComponentRepository.FindAll(); // Get all top designs 
            var model = _mapper.Map<List<TopComponentVM>>(tops);
            ViewBag.Progress = 25;
            ViewBag.ProgressLabel = "Top";
            ViewBag.Next = "Skirt";
            return View(model);
        }

        public IActionResult Skirt(int id)
        {
            _preferences["Top"] = id; // Add to preferences the top choice of the user
            var skirts = _skirtComponentRepository.FindAll(); // Get all skirt designs
            var model = _mapper.Map<List<SkirtComponentVM>>(skirts);
            ViewBag.Progress = 50;
            ViewBag.ProgressLabel = "Skirt";
            ViewBag.Next = "Sleeve";

            return View(model);
        }

        public IActionResult Sleeve(int id)
        {
            _preferences["Skirt"] = id; // Add to preferences the skirt choice of the user
            var sleeves = _sleeveComponentRepository.FindAll(); // Get all sleeve designs
            var model = _mapper.Map<List<SleeveComponentVM>>(sleeves);
            ViewBag.Progress = 75;
            ViewBag.ProgressLabel = "Sleeve";
            ViewBag.Next = "Recommend";

            return View(model);
        }

        public IActionResult Recommend(int id)
        {
            _preferences["Sleeve"] = id; // Add to preferences the sleeve choice of the user

            // Get the recommendations based on preferences
            var recommendations = _recommendationService.RecommnedDresses(_preferences); 
            var model = _mapper.Map<List<DressVM>>(recommendations);

            return View(model); // Display preferences
        }
    }
}

Sewit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sewit</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a href="#" class="navbar-brand">
                    <img src="~/photos/logo.png" height="28" alt="logo">
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="Sew" asp-action="Index"><span class="font-weight-bolder">Sewit</span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dresses
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <a class="dropdown-item" asp-controller="Design">Create</a>
                                    <a class="dropdown-item" asp-controller="Sew" asp-action="Top">Recommend</a>
                                }
                                else
                                {
                                    <a class="dropdown-item" asp-controller="Dress">List</a>

                                }
                            </div>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        { 
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarComp" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Components
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarComp">
                                    <a class="dropdown-item" asp-controller="Top" asp-action="Index">Top</a>
                                    <a class="dropdown-item" asp-controller="Skirt" asp-action="Index">Skirt</a>
                                    <a class="dropdown-item" asp-controller="Sleeve" asp-action="Index">Sleeve</a>
                                </div>

                            </li>
            }
            else
            {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Order" asp-action="Index">Cart</a>

                    </li>
            }

                    </ul>
                </div>

                <partial name="_LoginPartial.cshtml" />

            </div>
        </nav>
    </header>
    <main role="main" class="pb-3 min-vh-100">
        <div class="min-vh-100">
            @RenderBody()
        </div>
    </main>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>